version: "3.8"
services:
  rest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rest_api
    restart: unless-stopped
    ports:
      - "3006:3006"
    volumes:
      - ./:/code/
    # environment:
    #   - FLASK_ENV=development
    #   - FLASK_APP=app.py
